name: GitHub Actions Build and Deploy Demo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: Cleanup Worktree
        run: |
          git worktree prune
          rm -rf github-pages-deploy-action-temp-deployment-folder
          git worktree list
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: dist
